use "mvn.cmd" instead of "mvn" command on Windows. fixes #24
PaperMC/Paperclip pull request #25
Opened 2020-09-18 02:22 UTC by jmanpenilla

Checks for Windows OS using the "file.separator" System property.
https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html

2020-09-18 03:23 UTC, Proximyst requested changes

2020-09-18 03:23 UTC, Proximyst commented on java8/src/main/java/io/papermc/paperclip/Paperclip.java
> +        final String mavenCommand = System.getProperty("file.separator").contains("\\") ? "mvn.cmd" : "mvn";
Use the property `os.name`

2020-09-18 03:40 UTC, jmanpenilla commented on java8/src/main/java/io/papermc/paperclip/Paperclip.java
> +        final String mavenCommand = System.getProperty("file.separator").contains("\\") ? "mvn.cmd" : "mvn";
ok, updated

2020-09-18 03:42 UTC, Proximyst approved these changes

2020-09-27 06:52 UTC, kashike requested changes

2020-09-27 06:52 UTC, kashike commented on java8/src/main/java/io/papermc/paperclip/Paperclip.java
> +        final String mavenCommand = System.getProperty("os.name").toLowerCase().contains("windows") ? "mvn.cmd" : "mvn";
```suggestion
        final String mavenCommand = System.getProperty("os.name").toLowerCase(java.util.Locale.ENGLISH).contains("windows") ? "mvn.cmd" : "mvn";
```
Import the class.

2020-09-28 01:34 UTC, kashike approved these changes

2020-09-28 01:35 UTC, merged